import { describe, expect, it } from 'vitest';
import type { CommonTranslations } from '@/features/presentation/localization';
import { mapToBrandOverviewPageUIModel } from '../map-to-brand-overview-page-ui-model';

const translations = {
  appName: '',
  loading: '',
  error: 'Error',
  retry: '',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  confirm: '',
  search: '',
  noResults: '',
  healthStatus: '',
  connected: '',
  disconnected: '',
  getStarted: '',
  apiDocs: '',
  logout: '',
  pendingAccessTitle: '',
  pendingAccessMessage: '',
  brandGuidelinesAppName: '',
  brands: '',
  createBrand: '',
  brandNameLabel: 'Brand name',
  brandNamePlaceholder: '',
  descriptionLabel: '',
  descriptionPlaceholder: '',
  submit: '',
  noBrandsTitle: '',
  noBrandsBody: '',
  noBrandsCta: '',
  brandSettings: 'Brand settings',
  rename: 'Rename',
  deleteBrandConfirmTitle: 'Delete brand',
  deleteBrandConfirmBody: 'Are you sure?',
  editBrandVoice: '+ Edit brand voice',
  editVisualIdentity: '+ Edit visual identity',
  brandVoiceSectionTitle: 'Brand voice',
  visualIdentitySectionTitle: 'Visual identity',
  signOut: '',
  selectBrand: '',
  validationBrandNameRequired: 'Required',
  validationBrandNameTooLong: 'Too long',
  validationDescriptionTooLong: '',
  renameBrandTitle: 'Rename brand',
  deleteBrand: 'Delete brand',
  overview: '',
  brandVoice: '',
  visualIdentity: '',
  brandVoiceEditPageTitle: '',
  brandVoiceEmptyStateBody: '',
  brandVoiceToneOfVoiceLabel: '',
  brandVoicePreferredVocabularyLabel: '',
  brandVoiceRestrictedVocabularyLabel: '',
  brandVoiceMessagingPillarsLabel: '',
  brandVoiceWritingStyleRulesLabel: '',
  brandVoiceAudienceRulesLabel: '',
  brandVoiceApprovedPhrasesLabel: '',
  brandVoiceRejectedPhrasesLabel: '',
  brandVoiceAudienceRuleAudienceLabel: '',
  brandVoiceAudienceRuleRuleLabel: '',
  brandVoiceAddRow: '',
  brandVoiceRemoveRow: '',
  brandVoiceEmptyListPlaceholder: '',
  brandVoiceValidationToneTooLong: '',
  brandVoiceValidationListItemRequired: '',
  brandVoiceValidationListItemTooLong: '',
  brandVoiceValidationListItemDuplicate: '',
  brandVoiceValidationAudienceRequired: '',
  brandVoiceValidationRuleRequired: '',
  brandVoiceValidationListTooLong: '',
  visualIdentityEditPageTitle: '',
  visualIdentityEmptyStateBody: '',
  visualIdentityLogoUsageRulesLabel: '',
  visualIdentitySpacingLayoutGuidanceLabel: '',
  visualIdentityImageStyleGuidanceLabel: '',
  visualIdentityIconographyGuidanceLabel: '',
  visualIdentityUsageRestrictionsLabel: '',
  visualIdentityColourPaletteLabel: '',
  visualIdentityTypographyRulesLabel: '',
  visualIdentityColourPaletteNameLabel: '',
  visualIdentityColourPaletteHexLabel: '',
  visualIdentityColourPaletteUsageLabel: '',
  visualIdentityTypographyRoleLabel: '',
  visualIdentityTypographyFamilyLabel: '',
  visualIdentityTypographyWeightLabel: '',
  visualIdentityTypographySizeLabel: '',
  visualIdentityTypographyNotesLabel: '',
  visualIdentityAddRow: '',
  visualIdentityRemoveRow: '',
  visualIdentityEmptyListPlaceholder: '',
  dosAndDontsSectionTitle: '',
  dosAndDontsEmptyStateBody: '',
  addDosAndDontCta: '',
  editDosAndDontCta: '',
  deleteDosAndDontCta: '',
  dosAndDontTypeLabel: '',
  dosAndDontCategoryLabel: '',
  dosAndDontTitleLabel: '',
  dosAndDontBodyLabel: '',
  dosAndDontSuggestedCorrectionLabel: '',
  dosAndDontTypeDoLabel: '',
  dosAndDontTypeDontLabel: '',
  dosAndDontCategoryToneLabel: '',
  dosAndDontCategoryVocabularyLabel: '',
  dosAndDontCategoryVisualsLabel: '',
  dosAndDontCategoryLegalLabel: '',
  dosAndDontCategoryCampaignMessagingLabel: '',
  newDosAndDontPageTitle: '',
  editDosAndDontPageTitle: '',
  dosAndDontSubmitLabel: '',
  dosAndDontCancelLabel: '',
  dosAndDontSaveError: '',
  dosAndDontTitleRequiredError: '',
  dosAndDontTitleTooLongError: '',
  dosAndDontBodyRequiredError: '',
  dosAndDontBodyTooLongError: '',
  dosAndDontSuggestedCorrectionTooLongError: '',
  dosAndDontTypeRequiredError: '',
  dosAndDontCategoryRequiredError: '',
  deleteDosAndDontConfirmTitle: '',
  deleteDosAndDontConfirmBody: '',
  dosAndDontNotFound: '',
  contentCheck: '',
  contentCheckPageTitle: '',
  contentCheckActiveBrandLabel: '',
  contentCheckPastedTextLabel: '',
  contentCheckPastedTextPlaceholder: '',
  contentCheckCategoryLabel: '',
  contentCheckCategoryAllOption: '',
  contentCheckSubmitLabel: '',
  contentCheckReferenceTextLabel: '',
  contentCheckResultsTitle: '',
  contentCheckSuggestedCorrectionLabel: '',
  contentCheckNoActiveBrandTitle: '',
  contentCheckNoActiveBrandBody: '',
  contentCheckNoActiveBrandCta: '',
  contentCheckZeroMatchesTitle: '',
  contentCheckZeroMatchesBody: '',
  contentCheckZeroMatchesCta: '',
  contentCheckBrandNotFoundTitle: '',
  contentCheckBrandNotFoundBody: '',
  contentCheckBrandNotFoundCta: '',
  contentCheckLoadError: '',
  contentCheckPastedTextTooLongError: '',
} satisfies CommonTranslations;

const brand = {
  id: 'brand-1',
  ownerSubject: 'sub-1',
  name: 'Acme',
  description: null,
  createdAt: new Date('2026-05-15T00:00:00.000Z'),
  updatedAt: new Date('2026-05-15T00:00:00.000Z'),
};

describe('mapToBrandOverviewPageUIModel', () => {
  it('forwards labels and shaped sub-page hrefs for the present brand', () => {
    const model = mapToBrandOverviewPageUIModel({
      translations,
      brand,
      brandId: 'brand-1',
      isLoading: false,
      isError: false,
      notFound: false,
    });
    expect(model.brandName).toBe('Acme');
    expect(model.visualIdentityCtaHref).toBe('/brands/brand-1/visual-identity/edit');
    expect(model.renameModalTitle).toBe('Rename brand');
    expect(model.deleteConfirmLabel).toBe('Delete');
  });

  it('flags notFound separately from generic errors', () => {
    const model = mapToBrandOverviewPageUIModel({
      translations,
      brand: undefined,
      brandId: 'brand-1',
      isLoading: false,
      isError: true,
      notFound: true,
    });
    expect(model.notFound).toBe(true);
    expect(model.hasError).toBe(false);
  });

  it('surfaces the error label for non-404 failures', () => {
    const model = mapToBrandOverviewPageUIModel({
      translations,
      brand: undefined,
      brandId: 'brand-1',
      isLoading: false,
      isError: true,
      notFound: false,
    });
    expect(model.hasError).toBe(true);
    expect(model.errorLabel).toBe('Error');
  });
});
